print("Hello welcome to my first python project as begginer")
Name=input("What is your Name: ")
Birth_date=input("What is your year of birth?: ")
Age=2024-int(Birth_date)
print("Your name entered is: ",Name)
print("Your Year of birth is: ",Birth_date)
print(Age)